### ISSUE TITLE
Symlink resolution

### ISSUE THREAD

**Issue by scola84** [rollup/rollup-plugin-node-resolve#100] opened 2017-04-20 08:06 UTC
This line is wrong: https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L74

/project/packageA/index.js
/project/packageA/node_modules/async
/project/packageA/node_modules/packageB as symlink
/project/packageB/index.js

packageA includes packageB and packageB includes async. But async lives under packageA as per how npm installs packages (cf. https://docs.npmjs.com/cli/dedupe).

Now, because of the L74, packageB gets resolved to /project/packageB and rollup tries to import async from packageB/node_modules/async, which does not exist.

**Comment by bfred-it** [comment] 2017-06-22 09:07
Perhaps related to #98. Can you [provide a repro](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)?

**Comment by scola84** [comment] 2017-08-02 20:09
I've created https://github.com/scola84/rollup-plugin-node-resolve-100

**Comment by scola84** [comment] 2017-11-20 11:01
I solved my problem by setting `opts.main = false`. This will force `disregardResult = true` on line https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L65 which in turn will force skipping the if block starting at https://github.com/rollup/rollup-plugin-node-resolve/blob/master/src/index.js#L72

This works with the following plugins:
```
plugins: [
    resolve({
      main: false
    }),
    commonjs(),
    css({
      output: 'dist/browser.css'
    }),
    buble(),
    livereload({
      watch: 'dist',
      https: {
        ...
      }
    })
]
```

**Comment by whaaaley** [comment] 2019-04-09 21:47
Now that `main` has been deprecated in the latest version this workaround requires an alternative syntax to avoid the deprecation message.

```js
  resolve({ mainFields: ['module'] })
```

**Comment by bterlson** [comment] 2019-08-20 20:26
This no longer repros. Probably fixed by some of the recent symlinking improvements across this plugin, rollup-plugin-commonjs, and browserify/resolve. Please re-open if this is still an issue!

**Closed by bterlson** 2019-08-20 20:26 UTC
Labels: bug, has repro

**Comment by whaaaley** [comment] 2019-08-20 23:13
@bterlson Hello. 👋 

I just updated my rollup packages and commented out the workaround and the issue still seems to be present for me. What this screenshot is showing is that all the symlinks that I'm importing are not being found. I'm not sure if it matters, but the symlink that I'm using in my project is a relative softlink. In my project I have a root level folder called `shared` that I link into multiple apps' `src` folders like this.

```
ln -s ../../../shared apps/foobar/src
```

![image](https://user-images.githubusercontent.com/7419947/63390688-8b780780-c375-11e9-8225-cbf5af397fad.png)

**Comment by whaaaley** [comment] 2019-08-21 22:57
I reproduced the issue in this repository.
https://github.com/whaaaley/symlink-bug
