### ISSUE TITLE
Plugin breaks importing of local files

### ISSUE THREAD

**Issue by arschmitz** [rollup/rollup-plugin-node-resolve#122] opened 2017-11-15 14:44 UTC
When i add this plugin to roll up local imports such as `import thing from "./thing"` stop working removing the plugin resolves this issue. Is there a way to use the plugin without breaking local imports?

**Comment by revelt** [comment] 2017-11-30 16:21
I also came here troubleshooting the local imports. In my case, JSON was consumed by one dependency, deeper in the deps tree, and I get "Could not resolve" messages, being emitted by `rollup.js`:

```
[!] Error: Could not resolve './typos' from node_modules/get-pkg-repo/index.js
Error: Could not resolve './typos' from node_modules/get-pkg-repo/index.js
```

Since it's JSON being consumed, I thought adding a plugin `import json from 'rollup-plugin-json'` in Rollup config would solve this, but it does not. Maybe that plugin needs to be somehow fed into this plugin directly?!? Or maybe it's not a JSON issue and it's rather an issue with any local files?

**Comment by revelt** [comment] 2017-11-30 16:27
is this issue a duplicate of #88?

**Comment by revelt** [comment] 2017-11-30 16:33
Actually, I found the culprit, `get-pkg-repo` was consuming JSON which contained uppermost container as array, not as object.

**Comment by arschmitz** [comment] 2017-11-30 17:04
For my case i don't think it's a duplicate of #88 that this is not a dependency in package.json or anything like that its just a file (module) within the project. I'm not using any other plugins except for `rollup-plugin-node-resolve`. imports like `import thing from "./thing"` importing a file in the same directory work fine but as soon as i include this plugin the import now fails

**Comment by revelt** [comment] 2017-11-30 17:05
Withdrawing my accusation :) Note deleted.

**Comment by mecurc** [comment] 2019-05-05 22:46
Works fine now! Can be closed.

**Closed** 2019-05-06 10:32 UTC
