### ISSUE TITLE
browser field of package.json not resolved

### ISSUE THREAD

**Issue by AndyOGo** [rollup/rollup-plugin-node-resolve#156] opened 2018-04-30 13:28 UTC
We used to include [`nanomorph`](https://github.com/choojs/nanomorph) which uses node's assert built-in for the server but [replaces it by `nanoassert`](https://github.com/choojs/nanomorph/blob/master/package.json#L26-L28) for the browser.

Since we upgraded to version `3.3.0` we get following errors:

> 'assert' is imported by node_modules/nanomorph/index.js, but could not be resolved – treating it as an external dependency

> ‘assert’ is imported by commonjs-external:assert, but could not be resolved – treating it as an external dependency
Creating a browser bundle that depends on Node.js built-in module (‘assert’). You might need to include https://www.npmjs.com/package/rollup-plugin-node-builtins

Our rollup-config for this plugin includes the `browser: true` option as described in your usage.

**Solution:** we stay at version `3.0.0`!

**Comment by paulsouche** [comment] 2018-06-26 07:37
Hi,

Seems a duplicate of #136 and fixed by #143 but build fails and no news about it...

**Comment by luckhpy** [comment] 2018-09-23 19:37
i'm encounter with the same problem

**Comment by mecurc** [comment] 2019-05-05 22:29
Fixed by update version. Also, the bug was related to another package. They fix the issue. Can be closed now.

**Closed** 2019-05-05 22:38 UTC

**Comment by AndyOGo** [comment] 2019-05-06 08:09
@mecurc Thanks.
May I ask you to give us some more details about this other package? Name, version, etc.

**Comment by mecurc** [comment] 2019-05-06 08:12
it's here: https://github.com/choojs/nanomorph/pull/108/files

They just import assert instead of nanoassert.

**Comment by AndyOGo** [comment] 2019-05-06 08:49
@mecurc 
Thanks, I see.

Though as I understood, it's perfectly fine to rename modules by `browser` field, like they did it:
https://github.com/choojs/nanomorph/blob/43d39d01a9c14a8279e398bad93c1ef6edfa03a4/package.json#L27-L29

The `browser` field spec here:
https://github.com/defunctzombie/package-browser-field-spec

**Comment by melgenek** [comment] 2019-07-31 16:09
@mecurc I have a same similar issue with import of https://github.com/kelektiv/node-uuid. The browser override is not used in case of import with `import uuid from 'uuid/v4';` The https://www.npmjs.com/package/@types/uuid is used. A sample project that produces output with a wrong file included https://github.com/melgenek/uuid-typescript-rollup
